### PR TITLE
Add environment specific settings.php files and sane defaults for each environment

### PR DESCRIPTION
**Pull request by onnimonni**
We have had a problem that we can't use env effectively with servers that have 2 or more sites.

This pull request solves that problem and provides sane default configuration for future sites.

It adds:
* `settings.{development,stage,production}.php` files for environment specific configuration
* `settings.global.php` for shared configuration between sites so that config files can be DRY
* Symlinks those config files automatically for each site

Also I added the convention that we will use database naming scheme based on the environment where we run the site.

What this needs in addition is that Deploybot or Travis CI deploybot is used with that sites specific `WKV_SITE_ENV` in the building phase so for example for staging that would be:
```bash
$ cd drupal && WKV_SITE_ENV=stage ./build.sh
```

This allows us to symlink the correct files for that environment.

Also `build.sh` is now modified to fail if `WKV_SITE_ENV` is not set. Because otherwise people could really easily accidentally use development settings for production.

### CODE REVIEW

**Comment by maijs** [comment]
I'd also love to see this at the end of `settings.local.php` (or `settings.global.php`):
```
// Include per-developer settings overrides.
if (file_exists(__DIR__ . '/settings.private.php')) {
  include __DIR__ . '/settings.private.php';
}
```

The reason is that sometimes I want some thing tuned a bit differently than the environment defaults (twig cache on or off, or some config override) and at the same time I don't want to have it appear as changed in git cause it messes up the whole git rebase/checkout routine. #DX

**Comment by aleksijohansson** [comment]
@onnimonni As far as I know `./build.sh` script already accepts the environment as argument like this: `./build.sh update production`, but defaults to WKV_SITE_ENV if no argument is provided and if no WKV_SITE_ENV is provided it defaults to the default environment. If I've understood correctly this could already be used to differentiate dev and stage environments on the same server. That is of course limited to the `./build.sh`script. Is there some reason why you require WKV_SITE_ENV instead of relying on the already existing argument system? Doing nothing if the argument and WKV_SITE_ENV are both missing is smart I think to avoid accidents.

**Comment by onnimonni** [comment]
@aleksijohansson I didn't know about that and I think doing nothing is actually way better :)!

**Comment by onnimonni** [comment]
We agreed with @floretan and @maijs that we will symlink `settings.{development,stage,production},php to `sites/default/settings.php` instead so `sites/default/settings.local.php` can be removed from the repo and extra hacks can be place in that file in the future.

**Comment by tharna** [comment]
I feel like we are moving backwards with some of those changes. Like moving settings back under conf which was a complaint we got a lot from the old style setup. It's ok to realize we failed, but I would like to hear developers opinions on this one before rolling back.
Are we also still wanting to have multiple systems on same server? That will hold us back from having ephemeral instances in the future.

**Comment by onnimonni** [comment]
I totally agree that the ephemeral instances should be our end-goal. I still think that keeping the environment specific configuration files in git is not in conflict with that vision.

I can agree that the `conf/` location is a hack and the files should always be in the final location `sites/default/`. We could do something like this in `sites/default/settings.php`:

```php
/**
 * Keep this codebase DRY and include environment specific settings from another file
 */
if ( file_exists( __DIR__ . '/settings.' . WKV_SITE_ENV . '.php' ) ) {
    include __DIR__ . '/settings.' . WKV_SITE_ENV . '.php';
}
```

The problem with this is that I don't know how to refactor the drush configs to be site specific.
We can easily refactor the env from php-fpm to nginx server block with help of `fastcgi_param`.

**Pull request closed without merging**
